## Vectors in python

Import the numpy python module (so we can use function `np.array()` to create a vector). 

In [1]:
import numpy as np

Let's create a few vectors:

In [6]:
# First make it a list of values (we'll learn more about lists in 221)
list_1 = [1,2,3]

# Make it a vector using np.array:
vec_1 = np.array(list_1)

# Return vec_1 to check it out
vec_1

array([1, 2, 3])

Yay! our first vector in Python. Let's make another one. 

In [10]:
list_2 = [10, 100, 1000]
vec_2 = np.array(list_2)
vec_2

array([  10,  100, 1000])

### Basic vector operations

Let's do some basic vector math: addition, subtraction, scalar multiplication, and dot product. 

In [12]:
# Vector addition
vec_1 + vec_2

array([  11,  102, 1003])

Important note: this does *not* work if you use the original lists! What happens if you do `list_1 + list_2`? It does not treat these as vectors! 

In [17]:
list_1 + list_2

[1, 2, 3, 10, 100, 1000]

So using the `+` sign on lists APPENDS the elements from the second to the first. **Always look at the outputs of your steps!**

In [14]:
# Vector subtraction
vec_2 - vec_1

array([  9,  98, 997])

Dot product: use `np.dot()`

In [16]:
# Dot product:
np.dot(vec_1, vec_2)

3210

In [18]:
# Matrix multiplication:
5 * vec_2

array([  50,  500, 5000])

## Matrices in Python

In [19]:
# Make one 2 x 2 matrix: 
matrix_1 = np.matrix([[1, 9], 
               [6, 0]])
print(matrix_1)

# Make another 2 x 2 matrix: 
matrix_2 = np.matrix([[0, 2],
                      [3, 10]])
                      
print(matrix_2)

[[1 9]
 [6 0]]
[[ 0  2]
 [ 3 10]]


Try addition, subtraction and scalar multiplication: 

In [20]:
matrix_1 + matrix_2

matrix([[ 1, 11],
        [ 9, 10]])

In [21]:
matrix_1 - matrix_2

matrix([[  1,   7],
        [  3, -10]])

In [22]:
6 * matrix_1

matrix([[ 6, 54],
        [36,  0]])